In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\ameya\Dropbox\PC\Downloads\internship oasis infobyte\Titanic.csv")

In [4]:
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [6]:
df.isnull().sum()[df.isnull().sum()>0]

age           263
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.dtypes

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

In [11]:
df.select_dtypes(include='number').columns

Index(['pclass', 'survived', 'age', 'sibsp', 'parch', 'fare', 'body'], dtype='object')

In [13]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

# Missing data handling
#### **Age:** In age column there is numerical records so i used median. median is less affected than mean.
#### **Fare:** In Fare column there is numerical records so i used median and may contain extreme ticket prices.
#### **Embarked:** mode is used because it is categorical column and only a small number of values are missing.
#### **Cabin,Boat,Body,Home.dest:** These columns are not required because they have too many null values in it and not so important information for analysis

In [14]:
df['age'] = df['age'].fillna(df['age'].median())
df['fare'] = df['fare'].fillna(df['fare'].median())

In [16]:
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

In [18]:
df= df.drop(columns= ['cabin','boat','body','home.dest'])

In [19]:
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,S

In [22]:
df.isnull().sum()[df.isnull().sum()>0]

Series([], dtype: int64)

# Duplicate Removal
### In this there is no duplicate identified

In [25]:
df.duplicated().sum

np.int64(0)

# Standardisation
### Different formats were cleaned and converted into a common format for easier analysis.

In [38]:
df['sex'] = df['sex'].replace({'male':'Male','female': 'Female','m': 'Male','f':'Female'})

In [40]:
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",Female,29.0000,0,0,24160,211.3375,S
1,1,1,"Allison, Master. Hudson Trevor",Male,0.9167,1,2,113781,151.5500,S
2,1,0,"Allison, Miss. Helen Loraine",Female,2.0000,1,2,113781,151.5500,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",Male,30.0000,1,2,113781,151.5500,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",Female,25.0000,1,2,113781,151.5500,S

# Outlier Detection

In [51]:
for col in ['age','fare','sibsp','parch']:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    IQR = q3-q1

    low = q1 - 1.5*IQR
    up = q3 + 1.5*IQR

    outlier = df[(df[col] < low) | (df[col] > up)]

    print(col)
    print('outlier:', len(outlier))
    print('-----------')
    print('low limit:', low)
    print('up limit:', up)
    print('-----------')

age
outlier: 101
-----------
low limit: 2.5
up limit: 54.5
-----------
fare
outlier: 171
-----------
low limit: -27.172999999999995
up limit: 66.34379999999999
-----------
sibsp
outlier: 57
-----------
low limit: -1.5
up limit: 2.5
-----------
parch
outlier: 307
-----------
low limit: 0.0
up limit: 0.0
-----------

#### This is used to identify values in numerical columns. The detected outlier were retained because they can represent passenger information, rather than incorrect data.

# Data Type Correction

In [53]:
df.dtypes

pclass        int64
survived      int64
name         object
sex          object
age         float64
sibsp         int64
parch         int64
ticket       object
fare        float64
embarked     object
dtype: object

In [54]:
df['sex'] = df['sex'].astype('string')
df['name'] = df['name'].astype('string')
df['embarked'] = df['embarked'].astype('string')

In [60]:
df.dtypes

pclass               int64
survived             int64
name        string[python]
sex         string[python]
age                float64
sibsp                int64
parch                int64
ticket              object
fare               float64
embarked    string[python]
dtype: object

#### The data types were checked and changed were needed so that numerical columns are stored as number and text columns are stored as strings.

# Before VS After Summary

In [83]:
bf_null = df.isnull().sum()
bf_duplicate = df.duplicated().sum()
bf_rows = len(df)
bf_dtypes = df.dtypes

In [84]:
af_null = df.isnull().sum()
af_duplicate = df.duplicated().sum()
af_rows = len(df)
af_dtypes = df.dtypes

In [85]:
bf_count_dtypes = len(af_dtypes)
af_count_dtypes = len(df.dtypes)

In [93]:
summary = pd.DataFrame({
    'Content': [
        'Null Count',
        'Duplicate Count',
        'Row Count',
        'dtype Accuracy'
    ],
    'Before Cleaning': [
        bf_null,
        bf_duplicate,
        bf_rows,
        bf_count_dtypes
    ],
    'After Cleaning': [
        af_null,
        af_duplicate,
        af_rows,
        af_count_dtypes
    ]
})
summary

,Content,Before Cleaning,After Cleaning
0,Null Count,pclass 0 survived 0 name 0 sex ...,pclass 0 survived 0 name 0 sex ...
1,Duplicate Count,0,0
2,Row Count,1309,1309
3,dtype Accuracy,10,10

# Save the cleaned dataset to a new CSV file

In [94]:
df.to_csv('Titanic_cleaned_dataset.csv',index=False)

In [97]:
cl_df = pd.read_csv('Titanic_cleaned_dataset.csv')

In [98]:
cl_df.shape

(1309, 10)

In [100]:
cl_df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",Female,29.0000,0,0,24160,211.3375,S
1,1,1,"Allison, Master. Hudson Trevor",Male,0.9167,1,2,113781,151.5500,S
2,1,0,"Allison, Miss. Helen Loraine",Female,2.0000,1,2,113781,151.5500,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",Male,30.0000,1,2,113781,151.5500,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",Female,25.0000,1,2,113781,151.5500,S